---
title: "R Notebook"
output: html_notebook
---

load Kidney QTL viewer objects, they are downloaded from https://churchilllab.jax.org/qtlviewer/JAC/DOKidney

```{r}
library(qtl2)
data<-readRDS("~/Downloads/dataset.mrna.JAC_DO_kidney.v6.Rds")
load("~/Downloads/core.JAC_DO_kidney.v6.RData")
```

Download GRCm39 annotations from biomart, load gene list from pseudo references: /projects/omics_share/mouse/GRCm39/genome/sequence/imputed/rel_2112_v8/, merge 
```{r}
library(biomaRt)
ensembl <- useMart("ensembl", dataset="mmusculus_gene_ensembl", host="https://jul2023.archive.ensembl.org") # most recent GRCm39
annot<-getBM(c("ensembl_gene_id", "chromosome_name", "strand", "start_position", "end_position","gene_biotype"), mart=ensembl)
print(paste("# of genes in GRCm39 annotations from biomart: ",   length(annot$ensembl_gene_id)))
gene_list <- read.csv("~/Downloads/gene_list", header=FALSE)
colnames(gene_list) = c("gene_id")
print(paste("# of genes in pseudo references: ", length(gene_list$gene_id)))
gene_list2 <- intersect(gene_list$gene_id, dimnames(data$data$rz)[[2]] )
print(paste("# of genes in pseudo references and data: ", length(gene_list2)))
annot2<- annot[annot$ensembl_gene_id %in% gene_list2, ]
print(paste("# of genes in pseudo references, data and annotations: ", length(annot2$ensembl_gene_id)))
annot2 = annot2[annot2$chromosome_name != "Y", ]
print(paste("# of genes after removing genes on chrY", length(annot2$ensembl_gene_id)))
```

Find marker_id, check #ACE2 ENSMUSG00000015405, 
```{r}
find_marker_by_ensembl_id <- function(gene_id,annot2, markers) {
  gene_info <- annot2[annot2$ensembl_gene_id == gene_id, ]
  chr <- gene_info$chr
  pos <- gene_info$start_position/1e6
  marker_id <- find_marker(map, chr, pos = pos)
  return(marker_id)
}
gene_id = "ENSMUSG00000015405"
marker_id <- find_marker_by_ensembl_id(gene_id, annot2, markers) 
print(marker_id)
print("comparing to marker_id in annotation table:")
print(data$annot_mrna[data$annot_mrna$gene_id == gene_id,]$nearest_marker_id)
```

Generate covar martrix
```{r}
get_dat_dummpy<-function(dat, name){
  dat_unique = unique(dat)
  num_column = dim(dat_unique)[1] - 1
  num_row = dim(dat)[1]
  dat_dummy = matrix(0, nrow = num_row, ncol = num_column)
  print(dat_unique)
  col_names = c()
  for (i in 1:num_column) {
    d = levels(dat_unique[[1]])[i]
    print(d)
    coln = paste0(name, d)
    dat_dummy[dat == d,i] = 1
    col_names = append(col_names, coln)
  }
  colnames(dat_dummy) = col_names
  rownames(dat_dummy) = rownames(dat)
  return(dat_dummy)
}


data_annot<-as.data.frame( data$annot_samples)
sex <- data_annot[, "Sex", drop=FALSE]
rownames(sex) =  data_annot[,"Mouse.ID"]
age = data_annot[,"Age", drop=FALSE]
rownames(age) =data_annot[,"Mouse.ID"]
gen = data_annot[,"Gen", drop=FALSE]
rownames(gen) = data_annot[,"Mouse.ID"]
age = get_dat_dummpy(age, "age")
gen = get_dat_dummpy(gen, "gen")

covar = data.frame((sex[, "Sex"] == "M")*1)
colnames(covar) = "sex"
covar = cbind(covar, age)
covar = cbind(covar, gen)
head(covar)
```
Fit single-QTL model at a single position, calculate estimated coefficients for each gene

```{r}

res_coef = list()
for (gene_id in annot2$ensembl_gene_id){
  #print(gene_id)
  gene_info <- annot2[annot2$ensembl_gene_id == gene_id, ]
  chr <- gene_info$chr
  if (chr == "Y") next
  pos <- gene_info$start_position/1e6
  marker_id <- find_marker(map, chr, pos = pos)
  f = fit1(genoprobs[[chr]][,,marker_id], data$data$rz[,gene_id], addcovar = covar)
  res_coef[[gene_id]] = f$coef[c("A", "B", "C", "D", "E", "F", "G", "H")]
}
res_coef <- do.call("rbind", res_coef)
colnames(res_coef) <- c("A_J.39" ,"C57BL_6J.39",
             "129S1_SvImJ.39", "NOD_ShiLtJ.39",
             "NZO_HlLtJ.39", "CAST_EiJ.39",
             "PWK_PhJ.39", "WSB_EiJ.39")

write.csv(res_coef, "coef.csv") 
head(res_coef)
```

